version: "3.3"

services:
  # Dịch vụ Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - nextjs-app
      - certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/usr/share/nginx/html
    networks:
      - web

  # Dịch vụ Next.js
  nextjs-app:
    build:
      context: .
    container_name: nextjs-app
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    networks:
      - web

  # Dịch vụ Certbot để cấp SSL
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/usr/share/nginx/html
    entrypoint: >
      /bin/sh -c "trap exit TERM; 
      certbot certonly --webroot -w /usr/share/nginx/html -d phamngocphong.id.vn
      --non-interactive --agree-tos --email phongpham131102@gmail.com; 
      sleep 12h & wait $${!};"
    networks:
      - web

networks:
  web:
    driver: bridge
