version: "3.3"

services:
  # Dịch vụ Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - nextjs-app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/usr/share/nginx/html
    networks:
      - web

  # Dịch vụ Next.js
  nextjs-app:
    build:
      context: .
    container_name: nextjs-app
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - web

  # Dịch vụ Certbot để cấp SSL
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/usr/share/nginx/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - web

networks:
  web:
    driver: bridge
